### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by roozgar** [mikerabat/mrmath#2]
hi
how can i use this library?
in readme file you said compile!
i compiled the code with out error but how can use in my code ?!

**Comment by mikerabat** [comment]
Hi!

The library does not add any components to the component list but rather
exports
a few classes and interfaces. If only matrix operations are involved use
the matrix.pas unit
and you get the interfaces to to manipulate matrices. Let me know what
exactly you want to
do and I can of course help (and eventually update the docu ;) )

You can either check out the unit testing project that comes with the
library
(and is sometimes a useful source for examples) or
Check out a demo/example from here:
http://www.mrsoft.org/home/downloads.html

These are a few hints in the wiki provided with the library
https://github.com/mikerabat/mrmath/wiki

Hope this helps a bit.

kind regards
   Mike

**Comment by roozgar** [comment]
Thank you for the fast answer,
i need to inverse a n*n matrix at this time.

**Comment by mikerabat** [comment]
Hey...

check out the attached example - I hope that helps

kind regards
   Mike

**Comment by roozgar** [comment]
it seems the file is not attached well! :)

**Comment by mikerabat** [comment]
Hm... I replied via email.. seems it is not possible to attach a file...
Check out the following link:

[MatrixInverse example](https://mrsoft.org/Delphi/MatrixInverse.zip)

**Comment by Xor-el** [comment]
You either need t install madexcept OTR comments out a madexcept units for the meantime.

**Comment by mikerabat** [comment]
Sorry for that... I updated the project on that link without the MadExcept dependency.
Just download it again.

**Comment by roozgar** [comment]
thank you
work like a charm :))

tried to inverse 1000000 times with a 6*6 matrix
and it took about 5 seconds!

**Comment by mikerabat** [comment]
Seems to work ;)
