### ISSUE TITLE
LPK package

### ISSUE THREAD

**Issue by Alexey-T** [mikerabat/mrmath#3]
If you make .lpk Lazarus package file, them mrMath can be added to Lazarus OnlinePackageManager (seems).
you can create new package in Lazarus IDE, then add all pas files, then add description, save.

**Comment by mikerabat** [comment]
Thats cool. Is that for the new Lazarus 2.0 ide or also for older versions? And how do I do that exactyl?

Currently I'm mostly using CodeTyphoon IDE for the FPC development but adding the library to the online package manager sounds cool :)

**Comment by Alexey-T** [comment]
Its for Lazarus 1.8+. You add LPK file, then write to topic
http://forum.lazarus.freepascal.org/index.php/topic,34297.0.html
- ask to add package to OPM, GetMem will do it.

**Comment by zeljkoavramovic** [comment]
Current CodeTyphon package is in FPC directory. First I have renamed it to FPC-CodeTyphon. Then converted it into Lazarus package and put it into FPC-Lazarus directory. Content is attached. I have just checked and DLL gets compiled and 32-bit tests pass on FPC 3.2.1 and Lazarus 2.0.3.. Please ask GetMem to include it into Lazarus OnlinePackageManager for easy download.
[FPC-Lazarus.zip](https://github.com/mikerabat/mrmath/files/3344587/FPC-Lazarus.zip)

**Comment by Alexey-T** [comment]
To create LPK file - open Lazarus, use menu item "Package / New package", then save thus LPK in the folder of pas file. Then add all pas files to package using Toolbar in Package dlg.

**Comment by zeljkoavramovic** [comment]
It is better to have out of the box Lazarus experience then following some instructions. I would like to see that Lazarus is supported the same way as CodeTyphon is.

**Comment by Alexey-T** [comment]
I've sent PrvMail to GetMem.

**Comment by Alexey-T** [comment]
Your attachment is .lpi .lpr files - not OK, it's just project. LPK file is another thing.

**Comment by zeljkoavramovic** [comment]
You are fully right so please accept my apologies. Using ct2laz I have converted CodeTyphon project that produces a DLL library. I wrongly named it because it was in Packages directory, so that was probably what messed my thinking. Now it seams that I wrongly used this topic. Sorry for that, too.

**Comment by mikerabat** [comment]
I just added a Lazaraus package file: mrMath.lpr (and the lpi file) which should create the dll.
The process was actually quite straight forward and the lpr file is basically a copy of the codetyphon
file... I'll try to get that package to user "getmem" if you guys want...

**Comment by mikerabat** [comment]
And just added a lpk file...

**Comment by Alexey-T** [comment]
Notes for lpk file

- please move all .pas sources to MrMath/ or src/ subdir of the repo.
- rename .lpk file to mrMath_package.lpk (and its pas file too!) so it won't mess with mrMath DLL project (both now have the same base name- bad)

**Comment by mikerabat** [comment]
followed your last advice but I guess I will keep the src files in the base
