### ISSUE TITLE
I like mrmath. Great job

### ISSUE THREAD

**Issue by PassByYou888** [mikerabat/mrmath#4]
hi,mike,

why is the update time so long?

why stop submitting new projects?

are you busy with your work?

Best Regards
by.qq600585

**Comment by mikerabat** [comment]
What do you mean by update time? Actually features are coming into the project either by request or if I need something for work. Lately there was not much I needed for work ;) and no requests from the field. There is though something new upcoming.. KernelPCA is in the work. But anyhow the project itself mostly a hobby.
