### ISSUE TITLE
Fatal source bugs on compiling the FPC version of the unit

### ISSUE THREAD

**Issue by earthhist** [mikerabat/mrmath#7]
Fatal source bugs on compiling

==========
Windows 10
Clean new install of Lazarus 32 bit Latest version (v2.2.0)

What I had to do to get a compile

============
File mrmath_pkg.lpk
Remove 
Item 75 - file BufferedStream.pas

Looks like file does not exist

===========
File SimpleWinThreadPool.pas

comment out line 226, viz
SetThreadPoolProvider( {$IFDEF FPD}@{$ENDIF}SimpleWinThreadPoolProvdier );

reason: Identifier not found

==================
 File eigensystems.pas 

comment out line 3051 
  if abs( e^[m] ) <= eps2*abs( d^[m]*d[m + 1] ) then

Reason: Eigensystems.pas(3052,36) Error: Operator is not overloaded: "Double" * "TConstDoubleArr"

============

CONSEQUENCES in test of UNIT:

Test failed

TestEigValfromTridiagMtx
Exception: EAssertionFailedError
at $0067B388

==========

What is the fix?

**Comment by earthhist** [comment]
The fix for eigensystems .pas so works ok on the tests is

if abs( e^[m] ) <= eps2*abs( d^[m]*d^[m + 1] ) then

i.e there was a ^ missing

**Comment by mikerabat** [comment]
Dear user,

thanks for pointing that out. I will change that as soon as possible
(unfortunately the Delphi
compiler didn't complain here so it slipped through...).

I didn't intend though to put that code in the public eye though ;) it's
not quite there so the
current symmetric eigensystem functions still point to a different code
tree and this one will
be put into it's place when it's really ready.  I'm still in the process to
calculate the eigenvectors
from here...

kind regards
  Mike

**Comment by earthhist** [comment]
Hi Mike

> 
> I didn't intend though to put that code in the public eye though ;)
> it's not quite there so the current symmetric eigensystem functions
> still point to a different code tree and this one will be put into it's
> place when it's really ready. I'm still in the process to calculate the
> eigenvectors from here... 

But it *was* live code (at least on Freepascal. In my first comment 
on your website I had to comment out another line to make the program 
compile, which might be relevant.)  

To make it compile so I could check the rest of the program, I 
commented out the line 

if abs( e^[m] ) <= eps2*abs( d^[m]*d[m + 1] ) then

 so it always did the jump statement.  

The result was that the relevant *test routine failed*, as reported 
in my first comment.

Richard

> 
> kind regards
> Mike
> 
>

**Comment by mikerabat** [comment]
Just fixed according to your proposal and checked with my "CodeTyphoon" (my FPC installation) 32bit version. The Eigensystem tests run now through there.

**Comment by earthhist** [comment]
Very good.  Yes the tests worked for me when I made that change.

Did you check the two other issues I raised that caused Lazarus not 
to compile?  

1) The missing source file, and 
2) the conditional compile I had to comment out?

Richard

**Comment by mikerabat** [comment]
The source file was an initial idea to speed up loading of binary files - turned out that it was never needed... 
The last checkin removes that file and also removes the conditional compile from the thread pool file.

**Comment by mikerabat** [comment]
Let me know if that works for you now

**Comment by earthhist** [comment]
Yes works fine thanks

Richard
