### ISSUE TITLE
Line 94 of AVXMatrixOperations.pas should use ASMMoveOperationsx64

### ISSUE THREAD

**Issue by ReinierNL** [mikerabat/mrmath#8]
It misses the "x" of x64.

**Comment by ReinierNL** [comment]
It probably would be, but when I look at it, the "x" is missing. Are we looking at the same unit?
https://github.com/mikerabat/mrmath/blob/master/AVXMatrixOperations.pas

**Comment by mikerabat** [comment]
I think so… I see the avxmoveoperationsx64 there (and not the asm aka sse version)Von meinem iPhone gesendetAm 23.12.2022 um 15:15 schrieb Reinier Sterkenburg ***@***.***>:﻿
It probably would be, but when I look at it, the "x" is missing. Are we looking at the same unit?
https://github.com/mikerabat/mrmath/blob/master/AVXMatrixOperations.pas

**Comment by mikerabat** [comment]
Hi... sorry "lange Leitung" in German...
I looked at the wrong version of that file here on my local installation
and... it wasn't marked as changed in my subversion
unit...strange... I will check that as soon as possible

**Comment by mikerabat** [comment]
I removed that one.. thanks for the hint
